test_size: 0.2
n_components: 5
contamination: 0.05  # porcentaje estimado de outliers a remover
columns_to_scale:
  - totalCost
  - ecMaxContribution
  - ratio
  - pry_duration_m
  - num_org

columns_to_encode:
  - legalBasis
  - country1
  - cost0
